# application-qa.yaml

spring:
  datasource:
    url: jdbc:h2:mem:pigeon_db_qa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Enable swagger in QA
  swagger:
    enabled: true

  # Logging configuration
  logging:
    level:
      root: INFO