# application-test.yaml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pigeon_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  swagger:
    enabled: false

  logging:
    level:
      root: ERROR